name: kfx_dependency_injection
description: Flutter Dependency Injection library based on dotnet ServiceProvider
version: 1.5.0
homepage: https://github.com/JCKodel/kfx_dependency_injection

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.23.1

flutter:
  uses-material-design: true