name: kfx_dependency_injection
description: Flutter Dependency Injection library
version: 1.0.0
homepage: https://github.com/JCKodel/kfx_dependency_injection

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  test: ^1.22.0

flutter:
