name: kfx_dependency_injection
description: Flutter Dependency Injection library
version: 1.0.0
homepage: https://github.com/JCKodel/kfx_dependency_injection

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
